backend:
  name: git-gateway
  repo: PrairieCreekAdventures/prairie-creek-main
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/126852fe-13d7-45ec-a7fa-689aa3ac4700/pkce
  auth_token_endpoint: /sites/126852fe-13d7-45ec-a7fa-689aa3ac4700/token
  gateway_url: https://gateway.decapbridge.com

auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

logo_url: https://decapbridge.com/decapcms-with-bridge.svg
site_url: https://prairiecreekmain.netlify.app
display_url: https://prairiecreekmain.netlify.app

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    preview_path: "journal/{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Author"
        name: "author"
        widget: "string"
        default: "Kayla"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Category"
        name: "cat
